language: php

sudo: false

php:
  - 7.0

install:
  - composer install

before_script:
  - git clone https://github.com/krakjoe/pthreads
  - cd pthreads && phpize && ./configure && make install && cd ../

script:
  - phpdbg -qrr vendor/bin/phpunit tests --coverage-text
  - php -dextension=pthreads.so vendor/bin/phpunit tests
